---
{{- define "sample-lib-chart.route" -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.name }}
spec:
  port:
    targetPort: "8081"
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  wildcardPolicy: None
{{- end -}}
