apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-with-quarkus
    app.kubernetes.io/component: code-with-quarkus
    app.kubernetes.io/instance: code-with-quarkus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: quarkus
  name: code-with-quarkus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: code-with-quarkus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: code-with-quarkus
        deployment: code-with-quarkus
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: code-with-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: quay-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
