apiVersion: v1
kind: Service
metadata:
  labels:
    app: code-with-quarkus
    app.kubernetes.io/component: code-with-quarkus
    app.kubernetes.io/instance: code-with-quarkus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: quarkus
  name: code-with-quarkus
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: code-with-quarkus
    deployment: code-with-quarkus
  sessionAffinity: None
  type: ClusterIP
