apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.name }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: {{ .Values.name }}
    deployment: {{ .Values.name }}
  sessionAffinity: None
  type: ClusterIP
